Update Bootstrap
Zveltana/TodoList pull request #15
Opened 2023-07-06 14:11 UTC by Zveltana

CLose #13

2023-07-12 09:32 UTC, TBoileau requested changes

2023-07-12 09:32 UTC, TBoileau commented on package.json
> +        "bootstrap": "^5.2.3",
Pourquoi l'installer ici et ajouter les fichiers de la verison 5 dans le dossier "assets".

2023-07-12 09:39 UTC, Zveltana commented on package.json
> +        "bootstrap": "^5.2.3",
c'est soit l'un soit l'autre ?

2023-07-12 09:48 UTC, TBoileau commented on package.json
> +        "bootstrap": "^5.2.3",
Privilégie plutôt de passer par package.json

2023-07-12 10:12 UTC, Zveltana commented on package.json
> +        "bootstrap": "^5.2.3",
En ne mettant que la nouvelle version bootstrap et pas les fichiers, j'avais pas de changement visuel, c'est pour cela que j'ai mis les deux. Je vais mettre les anciens fichiers et laisser la nouvelle version bootstrap dans package.json alors

2023-07-12 10:19 UTC, TBoileau commented on package.json
> +        "bootstrap": "^5.2.3",
Oui mais il ne suffit pas d'installer bootstrap avec npm, il faut l'importer dans ton code.

2023-07-12 13:07 UTC, Zveltana commented on package.json
> +        "bootstrap": "^5.2.3",
il est déjà importer avec 

<!-- Bootstrap Core CSS -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ asset('shop-homepage.css') }}" rel="stylesheet">

2023-07-17 14:49 UTC, TBoileau commented on package.json
> +        "bootstrap": "^5.2.3",
Tu devrais importer ton bootstrap dans ton fichier css principal : 
```css
@import "~bootstrap/scss/bootstrap";
```

2023-07-17 16:04 UTC, merged